### ISSUE TITLE
App wont start

### ISSUE THREAD

**Issue by brokenbadger** [AdamGuidarini/MediTrak#123] opened 2024-10-24 19:48 UTC
Since last update, app crashes on boot screen (logo).
Cannot use.

**Comment by AdamGuidarini** [comment] 2024-10-24 21:07
Hello, sorry to hear that. Could you provide a few more details?

- What version of Android are you using?
- What do the schedules for your medications look like? Daily, multiple per day, other intervals?
- Do you medications have any non-alphanumeric characters in their, names, dosage units,  aliases, or instructions? I don't think this would cause it, but I usually don't use non-alphanumeric characters in my tests so it's something I may have missed

**Comment by K4LCIFER** [comment] 2024-10-24 23:52
I have the same issue. It's instantly crashing when I open the app. This only started occurring after using the most recent update v0.13.0. I'm on Android 15. App is installed via F-Droid.

**Comment by AdamGuidarini** [comment] 2024-10-25 04:14
Doing some tests with Android 15 in an emulator. I haven't been able to reproduce this yet. I installed version 0.12.9 first, created 1 medication with each type of schedule, letting the notifications trigger, checking a couple then updating to 0.13.0 and letting the notifications trigger again but haven't managed to encounter the issue yet.

Are there any details you'd be willing to share about the medications (schedule, dosage unit, etc..) that might help me recreate the issue in case it's related to the specific data?

It might also be worth trying to clear the app's cache. I'm not sure if it's in fact a data issue, but it might be worth trying

https://www.androidpolice.com/clear-app-cache-data-android/

**Comment by brokenbadger** [comment] 2024-10-25 06:10
Hi,

- I'm using android version 14
- My schedules are one medication at 08:00 and the other at 20:00 with reminders for both.
- Medications only use standard characters for both names and dosages.
- I've not changed anything since the previous version which worked perfectly. It worked perfectly before the update and now it just won't boot?
- I do use Nova launcher if thats of any consequence, but like I say, it ran flawlessly before?


Thanks for looking into this, app has been a must have for me.

**Comment by K4LCIFER** [comment] 2024-10-25 06:12
> It might also be worth trying to clear the app's cache. I'm not sure if it's in fact a data issue, but it might be worth trying

I cleared the cache, but the app still immediately crashes on open.

> Are there any details you'd be comfortable sharing about the medications (schedule, dosage unit, etc..) that might help me recreate the issue in case it's related to the specific data?

Not much comes to mind. The only thing that I do often that is possibly different than the usual flow is that I manually change dates/times in historic data, and I add custom units of "ug" to a medication on historic entries. 

One perhaps helpful note is that notifications from the app are still coming through for medication reminders.

**Comment by K4LCIFER** [comment] 2024-10-25 06:13
> I do use Nova launcher if thats of any consequence, but like I say, it ran flawlessly before?

I'm using the stock android launcher.

> Medications only use standard characters for both names and dosages.

Same for me, iirc.

**Comment by fleurc** [comment] 2024-10-25 13:27
Hi, I'm having the same issue, I'm running Android 14. My phone model is a Motorola Moto G54. The app was fine a few days ago, now with the recent update it just doesn't run.

**Comment by brokenbadger** [comment] 2024-10-25 14:49
Just upgraded to Android 15 and cleared cache, still same issue.
All other apps are also updated.

**Comment by AdamGuidarini** [comment] 2024-10-25 19:58
Hmm...Did you happen to have exported then imported data? I imported data from my own device into an instance of the app running in the emulator and it starts crashing immediately when I do that

**Comment by AdamGuidarini** [comment] 2024-10-25 20:04
The importer seems to be removing the last 0 from any date it gets (formatted like this: ```2024-10-25 04:30:00```). I've seen this in other parts of the app and there's a little band-aid fix for it (just adding a zero back). It's not ideal but it leaking out like this means a real fix needs higher priority

**Comment by AdamGuidarini** [comment] 2024-10-25 23:51
This release should fix this issue (assuming the bug in importing data was the cause). I'll close this issue, but if those doesn't fix the crashing feel free to reopen it or create a new one.

https://github.com/AdamGuidarini/MediTrak/releases/tag/v0.13.1

**Closed by AdamGuidarini** 2024-10-25 23:51 UTC
Labels: bug

**Comment by brokenbadger** [comment] 2024-10-26 07:04
> Hmm...Did you happen to have exported then imported data? I imported data from my own device into an instance of the app running in the emulator and it starts crashing immediately when I do that

No, not for me?

**Comment by K4LCIFER** [comment] 2024-10-26 07:30
> Hmm...Did you happen to have exported then imported data?

I didn't do that. I've exported, but I haven't imported.

**Comment by AdamGuidarini** [comment] 2024-10-26 16:59
Migrating this conversation of to a new issue as the fix doesn't seem to have worked: 

https://github.com/AdamGuidarini/MediTrak/issues/126

I left some instructions there for how to pull the app's logs. If anyone is able to retrieve them it would go a long way to helping me patch the bug as recreating this issue is still proving difficult
