### ISSUE TITLE
Reproducible Builds (for IzzyOnDroid)

### ISSUE THREAD

**Issue by obfusk** [AdamGuidarini/MediTrak#116] opened 2024-08-19 01:26 UTC
At IzzyOnDroid we support [Reproducible Builds](https://reproducible-builds.org/) (see: [Reproducible Builds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients?lang=en)).

Your app has been reproducible for quite a while :tada:. Unfortunately, the `.so` files in the APK contain an [ELF build-id](https://manpages.debian.org/bookworm/binutils-common/ld.1.en.html#build), which means the only way to create an identical build is to patch the cmake config to inject the same ones found in the release APKs, which requires manual work to keep up to date. It would be a lot easier for us if you could disable the build-id.

Adding `-DCMAKE_SHARED_LINKER_FLAGS=-Wl,--build-id=none` to the `externalNativeBuild.cmake.arguments` in `build.gradle` should accomplish this.

We'd appreciate if you could help making your build reproducible. We've prepared some [hints on Reproducible Builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds).

Thank you!

cc @IzzySoft

**Comment by AdamGuidarini** [comment] 2024-08-20 13:53
I can take care of that. Just added this to my current working branch, so it'll go out in the next release https://github.com/AdamGuidarini/MediTrak/commit/d67219d734bd5d4302fced2ea3c6b9f965aca806

But if it's more helpful to push it out sooner I can put out a release with just that change later today

**Comment by obfusk** [comment] 2024-08-20 15:40
Thanks! MediTrack already shows a green shield [here](https://apt.izzysoft.de/fdroid/index/apk/projects.medicationtracker). This change will mean less work for us *for future releases* but there's no rush to make a new release :)

![image](https://github.com/user-attachments/assets/b1f981c2-3fd4-4100-998a-bfd6d771c15f)

**Comment by AdamGuidarini** [comment] 2024-08-20 21:10
Sounds good! I'll close this issue for now then. Feel free to reopen it if something goes wrong or if something else needs to be added :)

**Closed by AdamGuidarini** 2024-08-20 21:10 UTC

**Comment by obfusk** [comment] 2024-10-22 15:41
`v0.13.0` is all good :tada: Thanks!

**Comment by IzzySoft** [comment] 2024-11-16 17:57
Just as a note @AdamGuidarini: dropping a tag and creating it with the identical name means it won't be picked up anymore.

```
--------------------------------------------------------------------------
-- RBLog                  [Update-Recipes] [projects.medicationtracker] --
--------------------------------------------------------------------------
Checking for recipe updates on 'projects.medicationtracker':
Using $GITHUB_TOKEN.
Updating 'projects.medicationtracker'...
Updates mode: 'tags:v[\\d.]+'.
Cloning 'https://github.com/AdamGuidarini/MediTrak.git'...
Cloning into '/tmp/tmpz9cb3i9p/repo'...
remote: Enumerating objects: 12895, done.
remote: Counting objects: 100% (3491/3491), done.
remote: Compressing objects: 100% (1095/1095), done.
remote: Total 12895 (delta 2075), reused 3256 (delta 1977), pack-reused 9404 (from 1)
Receiving objects: 100% (12895/12895), 20.54 MiB | 20.97 MiB/s, done.
Resolving deltas: 100% (7378/7378), done.
Found tag 'v0.13.3'.
Tag already present: 'v0.13.3'.
```

That was from the RB builder today. Same will happen in less than an hour with the repo updater which will claim "I already have a v0.13.3 here, so I'll ignore that release".

If you fix something and want the fix to reach those already having the unfixed release, please make a new one: increase `versionCode`, adjust `versionName`, create a new tag with its release and attach the fixed APK there.

Oh, and by removing the original release with its APK, you destroyed part of the RB proof btw :wink:

**Comment by IzzySoft** [comment] 2024-11-16 20:42
PS: I have to disable RB for your app until this is fixed. As you only have pre-releases, and the release name does not match the tag name, recipe updates fail. If I now change that manually, the next one will fail. This can be remedied by

* renaming the release to `v0.13.3`, pointing it to the `v0.13.3` tag (as that tag exists and points to the same commit, this should be no issue).
* creating a new release where tag name and release path match
* switch from pre-release to release, starting with the current one (v0.13.3) – that would enable us to use the Github API to find the needed details

Please give me a ping when solved so I can re-enable.

**Comment by AdamGuidarini** [comment] 2024-11-16 23:32
Just renamed ```v0.13.3 Fixed``` to ```v0.13.3``` and reused the tag of the same name. I also removed  the pre-release marker since that seems to have have life a bit more difficult before. I ended up deleting that last release with that tag because I used the wrong APK (I forgot to create a signed APK for it). Let me know if there's anything else I can do and sorry for the inconvenience 🙃

**Comment by IzzySoft** [comment] 2024-11-17 00:03
Looks good now, thanks! I've switched to "proper releases" at the RB builder, which picked up v0.13.3 fine ans succeeded with the build. Pushed & synced, and the green shield is up again in the repo as well. So all issues solved, wonderful!

The IoD repo is currently set up for pre-releases as well. If I switch that to disable them, both would only pick up "proper releases" – so if there's some "dev release" you don't want to be picked up, you could use pre-release for that. Shall we do that? Will your future "stable releases" from now on be "proper releases", so the IoD repo can/shall skip the pre-releases?

**Comment by AdamGuidarini** [comment] 2024-11-20 14:11
Sounds good, thank you!

**Comment by IzzySoft** [comment] 2025-01-08 18:25
@AdamGuidarini build for v0.13.6 failed – not just RB, but altogether:

```
> Task :app:lintVitalRelease FAILED
/build/repo/app/src/main/res/values-nl/strings.xml:158: Error: "garantie" is translated here but not found in default locale [ExtraTranslation]
    <string name="garantie">
            ~~~~~~~~~~~~~~~

   Explanation for issues of type "ExtraTranslation":
   If a string appears in a specific language translation file, but there is
   no corresponding string in the default locale, then this string is probably
   unused. (It's technically possible that your application is only intended
   to run in a specific locale, but it's still a good idea to provide a
   fallback.)

   Note that these strings can lead to crashes if the string is looked up on
   any locale not providing a translation, so it's important to clean them
   up.

1 errors, 0 warnings


FAILURE: Build failed with an exception.
```

Wonder how you got your APK created :see_no_evil:

**Comment by IzzySoft** [comment] 2025-01-08 19:04
PS: using `-x lintVitalRelease` it builds, but it's not RB. The embedded commit hash does not match the tagged commit, and even building from the embedded commit hash fails with huge differences. I guess the APK was built from a dirty tree, so nothing we can do: so v0.13.6 will be marked "RB failed" :cry:

**Comment by AdamGuidarini** [comment] 2025-01-10 02:20
The build might have been based on a different branch maybe. Just pushed a new release with translation fixes that I made sure was from the latest version of main

**Comment by IzzySoft** [comment] 2025-01-10 09:47
Thanks a lot! RB confirmed again for 0.13.7 :partying_face:

(also confirmed 0.13.6 was **not** built from the commit the tag points to :wink: But build failed for it even if the recipe adjusted to that using `git checkout <hash>` or `git reset --soft <hash>`. Not sure what happened there – but luckily that's fixed by now)
